README: update for iso link in example
dannf/ubuntu-server-netboot pull request #11
Opened 2021-02-10 16:47 UTC by tai271828

## Types of changes

- **Documentation Update**

## Description

20.04.2 is released and the original link for 20.04.1 does not work anymore.

## Additional context

Maybe we could use this link instead `http://old-releases.ubuntu.com/releases/focal/ubuntu-20.04.1-live-server-amd64.iso` so the link in the example will be more permanent.

2021-02-10 16:47 UTC, tai271828 commented
Please feel free to edit this pull request and merge it directly if the proposal is making sense to you : )

2021-04-01 22:27 UTC, dannf requested changes

2021-04-01 22:27 UTC, dannf commented on README.md
>  INFO: Downloading http://releases.ubuntu.com/focal/ubuntu-20.04.1-live-server-amd64.iso
I suppose for completion, can you update the `INFO:` line as well?

2021-04-26 12:48 UTC, tai271828 commented
I forgot to update this pull request, and now we have 234bd68402a555518b7fc5048c3ea43dfb8aeba6 , so let's close this ticket.

2021-04-26 12:48 UTC, closed without merging

2021-04-26 12:49 UTC, tai271828 commented
By the way, I enabled "allow maintainers to edit" by default, so @dannf maybe you would like to edit the pull request directly next time if you want.